### PR TITLE
add permissions to clusterlifecycle-state-metrics

### PR DESCRIPTION
**Pull request by elgnay**
The related jira: https://issues.redhat.com/browse/ACM-2163
Signed-off-by: Yang Le <yangle@redhat.com>

### CODE REVIEW

**Comment by elgnay** [comment]
> @elgnay Is this still awaiting PM review?

Yes, we can not merge it yet. PMs decided we can continue working on https://issues.redhat.com/browse/ACM-2163 in the first test sprint. That means we don't have to merge it in the dev sprint.

**Review by JakobGray — CHANGES_REQUESTED** [review]
Please run `go generate` and `make bundle` to update the bundle files

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
