### PR TITLE
add golimit to clusterclaim repos

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: ldpliu <daliu@redhat.com>

### CODE REVIEW

**Comment by ldpliu** [comment]
/hold
Need to confirm if it's needed to merge to mce 2.2

**Comment by skeeey** [comment]
LGTM

**Comment by JakobGray** [comment]
Since this didn't make code cutoff and isn't considered stop ship we'll wait until 2.2.1 is open for changes before merging

**Comment by ldpliu** [comment]
/unhold
@JakobGray Please help to review it , thanks

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
