### PR TITLE
add golimit to clusterclaim repos

### PR DESCRIPTION
**Pull request by ldpliu**
Signed-off-by: ldpliu <daliu@redhat.com>
https://issues.redhat.com/browse/ACM-2835

### CODE REVIEW

**Comment by ldpliu** [comment]
/hold 
Need to confirm if it's needed to fix in mce2.2

**Comment by ldpliu** [comment]
/hold 
Need to confirm if it's needed to fix in mce2.2

**Comment by skeeey** [comment]
LGTM

**Review by JakobGray — APPROVED** [review]

**Pull request merged**
