### PR TITLE
Read hosted cluster creds from secret in target ns

### PR DESCRIPTION
**Pull request by JakobGray**
Issue: https://github.com/stolostron/backlog/issues/26218

Signed-off-by: Jakob Gray <20209054+JakobGray@users.noreply.github.com>

### CODE REVIEW

**Comment by JakobGray** [comment]
/override "ci/prow/sonar-pre-submit" "SonarCloud Code Analysis"
Connection to remote cluster can't be reasonably unit tested

**Comment by ray-harris** [comment]
added "controllers/hosted.go" to sonar exclusion list. seeing if that fixes the sonar scan issues.

**Comment by ray-harris** [comment]
Excluding controllers/hosted.go helped, but didn't completely fix the issue. Need to bring this up with the delivering faster working group and CICD.

**Comment by JakobGray** [comment]
I'm not too worried about the coverage count, but looking for a code review.

**Pull request merged**
