### PR TITLE
Add manifests for the new cluster imageset controller

### PR DESCRIPTION
**Pull request by philipwu08**
New cluster imageset controller: https://issues.redhat.com/browse/ACM-1825

Signed-off-by: Philip Wu <phwu@redhat.com>

### CODE REVIEW

**Comment by ldpliu** [comment]
/assign @JakobGray 
Please please help to review it.
@philipwu08 We need to remove https://github.com/stolostron/multiclusterhub-operator/blob/main/pkg/templates/charts/toggle/console/templates/subscription-fast.yaml.  
And I also cut a branch for mce2.2  in https://github.com/stolostron/acm-hive-openshift-releases/tree/backplane-2.2, please use this branch in cluster imageset controller

**Comment by philipwu08** [comment]
@ldpliu Thanks! I've change the cluster image set controller to use the backplane-2.2 branch. Also, created issue for Jakob to remove the subscription: https://issues.redhat.com/browse/ACM-2117

**Comment by philipwu08** [comment]
Can't resolve dco task failure. Replacing with new PR: https://github.com/stolostron/backplane-operator/pull/342

**Pull request closed without merging**
