### PR TITLE
Picking up latest CRD from hypershift-deployment-controller.

### PR DESCRIPTION
**Pull request by jnpacker**
* Issue: https://github.com/stolostron/backlog/issues/22096
* Summary, we are keeping pace with Hypershift for Service Delivery consumption.

Signed-off-by: Joshua Packer <jpacker@redhat.com>

### CODE REVIEW

**Comment by zhujian7** [comment]
@jnpacker I think we can only merge this PR until the `backplane-operator` branch `backplane-2.10` stops FF'd, what do you think?

**Comment by JakobGray** [comment]
Is this not supposed to go into MCE 2.0?

**Comment by jnpacker** [comment]
Yes. We want it in 2.0, we bumped all the the other parts of hypershift to get a change for SD.

**Comment by jnpacker** [comment]
Our plan as a cloud first development cycle for this hypershift-deployment-controller and hypershift-addon-operator project is to FF to both BP-2.0 and BP-2.1 until BP-2.1 is released, then we will FF BP-2.1 and BP-2.2 till 2.2 is released.  

This means that we plan to see if we can cloud deliver hypershift through 2.0 till 2.1 is released.

As this is behind a feature flag, it has been deemed a low risks. FYI @gebhardtr

**Pull request merged**
