### PR TITLE
ACM-10734: Remove obsolete hypershift related image references

### PR DESCRIPTION
**Pull request by rokej**
# Description

With https://issues.redhat.com/browse/HYPBLD-249, the following MCE container images are no longer built and packaged in MCE. This PR is to remove references to those images from the hypershift addon installation chart.

## Related Issue

https://issues.redhat.com/browse/HYPBLD-249

## Changes Made

With https://issues.redhat.com/browse/HYPBLD-249, the following MCE container images are no longer built and packaged in MCE. This PR is to remove references to those images from the hypershift addon installation char

## Screenshots (if applicable)

Add screenshots or GIFs that demonstrate the changes visually, if relevant.

## Checklist

- [ ] I have tested the changes locally and they are functioning as expected.
- [ ] I have updated the documentation (if necessary) to reflect the changes.
- [ ] I have added/updated relevant unit tests (if applicable).
- [ ] I have ensured that my code follows the project's coding standards.
- [ ] I have checked for any potential security issues and addressed them.
- [ ] I have added necessary comments to the code, especially in complex or unclear sections.
- [ ] I have rebased my branch on top of the latest main/master branch.

## Additional Notes

Add any additional notes, context, or information that might be helpful for reviewers.

## Reviewers

Tag the appropriate reviewers who should review this pull request. To add reviewers, please add the following line: `/cc @reviewer1 @reviewer2`

## Definition of Done

- [ ] Code is reviewed.
- [ ] Code is tested.
- [ ] Documentation is updated.
- [ ] All checks and tests pass.
- [ ] Approved by at least one reviewer.
- [ ] Merged into the main/master branch.

### CODE REVIEW

**Comment by rokej** [comment]
@dislbenn @JakobGray Could you please look into the two test failures?

**Comment by dislbenn** [comment]
@rokej the issue that is occurring is due to a package dependency that was upgraded that we're depending on: https://github.com/stolostron/multiclusterhub-operator/pull/1404. We will create a PR in this repo to fix the issue today.

**Comment by dislbenn** [comment]
@rokej if you rebase the latest changes from main into your branch, that should resolve the issue: https://github.com/stolostron/backplane-operator/pull/647

**Comment by dislbenn** [comment]
Closing this PR and will merge: https://github.com/stolostron/backplane-operator/pull/648

**Pull request closed without merging**
