### PR TITLE
support addondeploymentconfig for work mgr

### PR DESCRIPTION
**Pull request by skeeey**
Signed-off-by: Wei Liu <liuweixa@redhat.com>

### CODE REVIEW

**Comment by skeeey** [comment]
refer to https://github.com/stolostron/backlog/issues/26488

**Comment by skeeey** [comment]
@JakobGray could you help me to take a loot at unit test? it failed at `ensuring the deployment image is overridden`, I think my change should not affect this part, but it keeps failing, thanks

**Comment by JakobGray** [comment]
@skeeey Error is `"error applying object Name: work-manager Kind: ClusterManagementAddOn: failed to create typed patch object: .spec.supportedConfigs: field not declared in schema"`. This is from using a new field `supportedConfigs` added to the 0.9.0 version of the ClusterManagementAddOn API. The operator was using the previous version so I have updated it to the newest.

**Pull request merged**
