### PR TITLE
Change ReplicaCount to 1 for HyperShiftDeployment

### PR DESCRIPTION
**Pull request by zkayyali812**
Signed-off-by: Zachary Kayyali <zkayyali@redhat.com>

### CODE REVIEW

**Comment by jnpacker** [comment]
I see that the addon is only replicaCount 1, so is that hard coded to 1?

**Comment by zkayyali812** [comment]
Yes, setting it to 1 explicitly hardcodes it to 1 here.

The MCE/MCH will not override the replica in this case

**Comment by jnpacker** [comment]
Answered my own question. They hard code to 1.

**Pull request merged**
