### PR TITLE
Import local cluster

### PR DESCRIPTION
**Pull request by ray-harris**

### CODE REVIEW

**Comment by ray-harris** [comment]
/hold

Still needs unit and functional tests.

**Comment by JakobGray** [comment]
What's missing is a way to monitor the status of the existing ManagedCluster. This could be it's own `StatusReporter` similar to how we do `ClusterManagerStatus`. The way we map status in MCH is in [mapManagedClusterConditions](https://github.com/stolostron/multiclusterhub-operator/blob/main/controllers/status.go#L394)

**Pull request closed without merging**
